In [1]:
import mysql.connector
from mysql.connector import Error


#### CONNECT TO GOOGLE CLOUD MYSQL
config = {
    'user': 'root',
    'password': 'txybkx5kPMpko8C6',
    'host': '35.238.14.103', 
    'database': 'ddx_db'
}
cnxn = mysql.connector.connect(**config)

#### BASIC QUERY FUNCTIONS

# Read query, something like a select
def read_query(connection, query):
    cursor = connection.cursor()
    result = None
    try:
        cursor.execute(query)
        result = cursor.fetchall()
        return result
    except Error as err:
        print(f"Error: '{err}'")
        
### HELPER FUNCTIONS

# Input: list from query, col names
def list_to_df(ls, cols):
    return pd.DataFrame(ls, columns=cols)

In [2]:
# Query NBA Game Data to get dataset
import pandas as pd

q1 = """
SELECT * FROM nba_game_data;
"""

nba_game_data = read_query(cnxn, q1)
#print(nba_game_data)
cols = box_stats = ['id', 'gid', 'team', 'fg', 'fga', 'fg_pct', 'fg3', 'fg3a', 'fg3_pct', 'ft', 'fta', 'ft_pct', 'orb', 'drb', 'trb', 'ast', 'stl', 'blk', 'tov', 'pf', 'ts_pct', 'efg_pct', 'fg3a_per_fga_pct', 'fta_per_fga_pct', 'orb_pct', 'drb_pct', 'trb_pct', 'ast_pct', 'stl_pct', 'blk_pct', 'tov_pct', 'off_rtg', 'def_rtg', 'pts', 'date']
ngd_df = pd.DataFrame(nba_game_data, columns=cols)

print(ngd_df.columns)
ngd_df.head()

Index(['id', 'gid', 'team', 'fg', 'fga', 'fg_pct', 'fg3', 'fg3a', 'fg3_pct',
       'ft', 'fta', 'ft_pct', 'orb', 'drb', 'trb', 'ast', 'stl', 'blk', 'tov',
       'pf', 'ts_pct', 'efg_pct', 'fg3a_per_fga_pct', 'fta_per_fga_pct',
       'orb_pct', 'drb_pct', 'trb_pct', 'ast_pct', 'stl_pct', 'blk_pct',
       'tov_pct', 'off_rtg', 'def_rtg', 'pts', 'date'],
      dtype='object')

,id,gid,team,fg,fga,fg_pct,fg3,fg3a,fg3_pct,ft,...,drb_pct,trb_pct,ast_pct,stl_pct,blk_pct,tov_pct,off_rtg,def_rtg,pts,date
0,1,/boxscores/202012230TOR.html,nop,42,80,0.525,19,42,0.452,10,...,22.2,84.1,56.3,71.4,12.5,16.3,21.3,108.6,95.2,20201223
1,2,/boxscores/202012230TOR.html,tor,38,89,0.427,14,46,0.304,9,...,15.9,77.8,43.8,68.4,9.6,13.2,17.5,95.2,108.6,20201223
2,3,/boxscores/202012310TOR.html,nyk,32,88,0.364,3,36,0.083,16,...,17.0,81.3,47.5,65.6,6.0,9.7,13.4,83.7,100.8,20201231
3,4,/boxscores/202012310TOR.html,tor,34,83,0.410,17,52,0.327,15,...,18.8,83.0,52.5,61.8,7.1,11.5,14.8,100.8,83.7,20201231
4,5,/boxscores/202101040TOR.html,bos,41,84,0.488,15,29,0.517,29,...,29.3,84.6,60.2,46.3,2.9,17.0,16.1,120.3,108.9,20210104

In [3]:
## Queries

# Select last 10 games

# Select torontos (tor) teams games

In [4]:
# Aggregate Functions

## Get each teams average points per game

## Get each teams average stats per game

In [ ]:
# Queries and Aggregate Functions

## Rank Each team by average assists per game